#!/bin/bash
set -e

cpu=4
ram=6144
osk="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"
opt="+invtsc,+ssse3,+sse4.2,+popcnt,+avx,+aes,+xsave,+xsaveopt,check"

vars=OVMF_VARS.fd
[ ! -f $vars ] && cp /usr/share/ovmf/x64/OVMF_VARS.fd $vars

qemu-system-x86_64 \
  -enable-kvm -M q35 -m $ram -smp $cpu \
  -smbios type=2 -cpu Penryn,vendor=GenuineIntel,kvm=on,vmware-cpuid-freq=on,$opt \
  -usb -device usb-kbd -device usb-tablet \
  -device usb-ehci,id=ehci -device nec-usb-xhci,id=xhci -global nec-usb-xhci.msi=off \
  -device isa-applesmc,osk="$osk" \
  -device ich9-intel-hda -device hda-duplex \
  -device ich9-ahci,id=sata \
  -device ide-hd,bus=sata.2,drive=opencore \
  -device ide-hd,bus=sata.3,drive=installer \
  -device ide-hd,bus=sata.4,drive=macos \
  -device virtio-vga -display gtk \
  -drive if=pflash,format=raw,readonly=on,file=/usr/share/ovmf/x64/OVMF_CODE.fd \
  -drive if=pflash,format=raw,file=$vars \
  -drive id=opencore,if=none,snapshot=on,format=raw,file=opencore.img \
  -drive id=installer,if=none,file=installer.qcow2,format=qcow2 \
  -drive id=macos,if=none,file=macos.qcow2,format=qcow2 \
  -netdev user,id=net0 -device virtio-net-pci,netdev=net0,id=net0,mac=52:54:00:c9:18:27 \
  -monitor stdio
